package network.protocol;

public enum MessageType {
  REGISTER_REQUEST,
  LOGIN_REQUEST,
  TOKEN_LOGIN_REQUEST,
  LOGOUT_REQUEST,
  SECURITY_QUESTION_REQUEST,
  PASSWORD_RESET,
  RENAME_REQUEST,
  MATCHMAKING_REQUEST,
  MATCHMAKING_CANCEL,
  MATCH_INVITE,
  MATCH_INVITE_DECISION,
  GAME_ACTION,
  REACTION,
  LEADERBOARD_REQUEST,
  SCORE_SUBMISSION,
  PROFILE_UPDATE,
  PING,

  REGISTER_RESPONSE,
  LOGIN_RESPONSE,
  SECURITY_QUESTION_RESPONSE,
  RENAME_RESPONSE,
  LEADERBOARD_RESPONSE,
  SCORE_RESPONSE,
  PROFILE_RESPONSE,
  ACK,
  PONG,
  ERROR,

  MATCH_FOUND,
  MATCH_INVITE_EVENT,
  MATCH_STATE_UPDATE,
  MATCH_ENDED,
  REACTION_EVENT
}
